### ISSUE TITLE
Mouse input doesn't work

### ISSUE THREAD

**Issue by terrybrashaw** [jwilm/alacritty#1142]
**Which operating system does the issue occur on?**
Void Linux

**If on linux, are you using X11 or Wayland?**
X11

**Which version of Alacritty?**
Master (f298ebb2179eff947cdb9cb7a4bd96e9739eac5c)

Applications which accept mouse input either don't react at all or react in a broken way. For example: [Cmus](https://cmus.github.io/) and [Ranger](https://github.com/ranger/ranger); both support mouse input for selecting items in their interfaces but this doesn't work in a *bare* Alacritty terminal. However, running tmux inside Alacritty and using any mouse-enabled application through tmux, mouse input works perfectly fine.

It seems Alacritty *is* sending input, but *incorrect* input? In Neovim, with mouse input enabled, clicking a line shows `23m` in the command window in the bottom right (where "23" corresponds to the line being selected). And does nothing else. 

What's strange is I've been using Alacritty for about 3 weeks and I had this problem when I first installed it, but it went away after a few days and I have no idea what changed. Alacritty's been working fine until a few days ago and, again, I have no idea what changed.

Oh and for comparison, xterm works as expected on my machine (without tmux).

**Comment by chrisduerr** [comment]
Does https://github.com/jwilm/alacritty/pull/1141 fix this?

**Comment by terrybrashaw** [comment]
#1141 does not fix the problem.

**Comment by chrisduerr** [comment]
I'll look into this once I've got the time, might be able to include it into #1141 if the fix isn't too complicated.

**Comment by chrisduerr** [comment]
@terrybrashaw Please try running #1141 again and make sure you remember to recompile it before executing the binary. Inside `ranger` mouse support should work with #1141.

**Comment by chrisduerr** [comment]
I've tested `cmus` too and it doesn't work in `xterm` either, so it seems like mouse is not (or at least not properly) supported inside `cmus`.

**Comment by terrybrashaw** [comment]
Oh no, my mistake. I assumed the changes were merged to your master branch.

#1141 *does* fix the problem. :tada: 

Sorry @chrisduerr!

**Comment by chrisduerr** [comment]
No problem, glad this PR was able to help you! :)

**Comment by chrisduerr** [comment]
Does it work inside of xterm but not alacritty (with the PR)? Maybe I'm just using `cmus` wrong, I haven't used it before.

**Comment by terrybrashaw** [comment]
Correct. In fact, both Cmus and Ranger work as expected inside xterm, but not Alacritty without #1141.

However, Neovim still doesn't work inside Alacritty even with #1141. But Neovim doesn't work inside xterm either.

**Comment by terrybrashaw** [comment]
Also, you have to `:set mouse=true` in cmus for mouse input.

**Comment by chrisduerr** [comment]
You have to use `:set mouse=a` to make xterm or alacritty work with neovim.

Looks like everything is working then when #1141 is merged. Awesome!

**Comment by terrybrashaw** [comment]
Hmm...I've got `:set mouse=a` in Neovim and it doesn't work in Alacritty or xterm on my machine.

Neovim works in either one through tmux though.

**Comment by NickeZ** [comment]
I confirm, using pull request #1141, mouse doesn't work in either tmux nor neovim nor neovim in tmux.

**Comment by chrisduerr** [comment]
That's odd, I tested it and it worked at one point, I've probably made a change to break it again, thanks for the notice.

**Comment by chrisduerr** [comment]
Turns out not only does `1000` activate mouse clicks, but `1002` does too, should be fixed now.

**Comment by terrybrashaw** [comment]
Neovim, Cmus and Ranger all work inside Tmux with those changes but now Cmus and Ranger are broken in bare Alacritty.

Here's what's happening on my end: https://www.youtube.com/watch?v=p99O8V0QWag

**Comment by chrisduerr** [comment]
I've tested the latest commit in that PR with `ranger`, `htop`, `vim` and `kakoune`.
All of them seem to work just fine.

Please make sure you're testing the commit 237ac468750d9f536819dbd2d973c1598c6074b7.

**Comment by terrybrashaw** [comment]
Looks good.

Neovim in Alacritty without Tmux is still broken but at least most things work now.

**Comment by chrisduerr** [comment]
If you use `:set mouse=a` in neovim with the last commit of that PR neovim should work. I don't use tmux and it works great for me, make sure your neovim config isn't messing with things or something like that.

It *should* all be good.

**Comment by terrybrashaw** [comment]
I have `set mouse=a` in my nvim config and I've tried manually setting it as well. Still broken.

I show what's happening in nvim inside and outside of tmux here: https://youtu.be/p99O8V0QWag?t=1m25s

That part is still accurate even on https://github.com/jwilm/alacritty/pull/1141/commits/237ac468750d9f536819dbd2d973c1598c6074b7

**Comment by NickeZ** [comment]
Now everything works for me as well.

**Comment by terrybrashaw** [comment]
Something on my machine is messing with nvim then. 

This issue can be closed when https://github.com/jwilm/alacritty/pull/1141 is pulled. Good work @chrisduerr!

**Comment by NickeZ** [comment]
@terrybrashaw try launching neovim with `vim -u NORC` and then manually do `:set mouse=a` to verify that nothing in your config / your plugins mess with your vim =)

**Comment by terrybrashaw** [comment]
@NickeZ Tried that already with the same result. :/

Maybe I need nightly neovim.

**Comment by terrybrashaw** [comment]
Problem solved. I needed nightly neovim, or there was an optional dependency left out in my package manager's version of neovim. :D

**Comment by chrisduerr** [comment]
Is there any issue left @terrybrashaw? If not, please close this issue.

**Comment by terrybrashaw** [comment]
If it's merged into jwilm/alacritty, then all's good. :+1:

**Comment by xerron** [comment]
work in neovim but not in vim 8.1

**Comment by xerron** [comment]
``` vim
if has('mouse')
    set mouse=a
endif

if !has('nvim')
  set ttymouse=xterm2
endif

```
