### ISSUE TITLE
Newline in neovim makes text glitch with line numbers enabled

### ISSUE THREAD

**Issue by cr0sh** [jwilm/alacritty#2005]
Which operating system does the issue occur on?

Windows 10, version 1809(build 17763.253)

Steps to reproduce:
1. Open default alacritty.yml(for example) with nvim
![image](https://user-images.githubusercontent.com/13118114/51085497-8b7bad80-177d-11e9-9bae-10fb55b38938.png)
2. (In normal mode) Press `<o>`, `<CR>`, `<CR>`
![image](https://user-images.githubusercontent.com/13118114/51085505-b239e400-177d-11e9-94b0-b3b433c4b763.png)

Refreshing window with `<C-D>` and `<C-U>` multiple times cleans glitches.
This does not happen after ":set nonumbers", I don't have idea to solve this with numbers on.
I tested on neovim 0.3.2.88-beta(latest? pakage in chocolatey) and 0.4.0-126(nightly build)

**Comment by chrisduerr** [comment]
Does this happen with both ConPTY and WinPTY?

**Comment by chrisduerr** [comment]
@cr0sh Just to make sure, please check that during startup it is explicitly mentioned that it's running ConPTY not WinPTY (you can see it when running `alacritty -v`).

**Comment by cr0sh** [comment]
```text
PS C:\Users\ska82\Documents\alacritty> .\alacritty -v
PS C:\Users\ska82\Documents\alacritty> Created log file at "C:\\Users\\ska82\\AppData\\Local\\Temp\\Alacritty-14568.log"
[2019-01-14 20:38] [INFO] Welcome to Alacritty
[2019-01-14 20:38] [INFO] Configuration loaded from "C:\\Users\\ska82\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2019-01-14 20:38] [INFO] Device pixel ratio: 1.25
[2019-01-14 20:38] [INFO] Width: 1280, Height: 960
[2019-01-14 20:38] [INFO] Initializing glyph cache...
[2019-01-14 20:38] [INFO] ... finished initializing glyph cache in 0.0466501s
[2019-01-14 20:38] [INFO] Width: 1280, Height: 960
[2019-01-14 20:38] [INFO] Cell Size: (10 x 24)
[2019-01-14 20:38] [INFO] Padding: (2.5 x 2.5)
[2019-01-14 20:38] [INFO] PTY Dimensions: Line(39) x Column(127)
[2019-01-14 20:38] [INFO] Using Winpty agent
[2019-01-14 20:38] [INFO] Initialisation complete
[2019-01-14 20:38] [INFO] Font size changed to Size(27) with DPR of 1.25
[2019-01-14 20:38] [INFO] Width: 1280, Height: 960
```
```text
PS C:\Users\ska82\Documents\alacritty> .\alacritty -v
PS C:\Users\ska82\Documents\alacritty> ^Ceated log file at "C:\\Users\\ska82\\AppData\\Local\\Temp\\Alacritty-16060.log"
PS C:\Users\ska82\Documents\alacritty> acritty
[2019-01-14 20:39] [INFO] Configuration loaded from "C:\\Users\\ska82\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2019-01-14 20:39] [INFO] Device pixel ratio: 1.25
[2019-01-14 20:39] [INFO] Width: 1280, Height: 960
[2019-01-14 20:39] [INFO] Initializing glyph cache...
[2019-01-14 20:39] [INFO] ... finished initializing glyph cache in 0.0678048s
[2019-01-14 20:39] [INFO] Width: 1280, Height: 960
[2019-01-14 20:39] [INFO] Cell Size: (10 x 24)
[2019-01-14 20:39] [INFO] Padding: (2.5 x 2.5)
[2019-01-14 20:39] [INFO] PTY Dimensions: Line(39) x Column(127)
[2019-01-14 20:39] [INFO] Using Conpty agent
[2019-01-14 20:39] [INFO] Initialisation complete
[2019-01-14 20:39] [INFO] Font size changed to Size(27) with DPR of 1.25
[2019-01-14 20:39] [INFO] Width: 1280, Height: 960
```

I tried both ConPTY and WinPTY with 0.2.5. Same result.

**Comment by chrisduerr** [comment]
Thanks a ton for the update! Looks like it is indeed present for all Windows backends.

**Comment by abulimov** [comment]
Actually I've tried same steps in normal PowerShell console, and got same corruption, so it seems the issue is with NeoVim on Windows, not with Alacritty.

**Comment by rehnarama** [comment]
Does anyone know if there is an upstream issue of this anywhere?

**Comment by mbudde** [comment]
Should be fixed in Neovim master: https://github.com/neovim/neovim/issues/9461

**Comment by gaving** [comment]
Does anyone know how I could further debug this sort of thing? Going slowly mad because of it.

I've this rendering glitch going on:-

![image](https://user-images.githubusercontent.com/43741/99371943-74e19880-28b7-11eb-8312-013969267079.png)

Latest neovim nightly, alacritty 0.5.0. Windows 10 running WSL1.

```
 nvim --version
Found existing alias for "nvim". You should use: "v"
NVIM v0.5.0-828-g0a95549d6
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parame
ter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -
fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FRO
M -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/
neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bo
t-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-abaca5c2-51e7-4cf1-bc06-8cf3e644ab24

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

```
❯ echo $TERM
screen-256color
```

```
❯ alacritty -vv
Created log file at "C:\Users\1352152\AppData\Local\Temp\Alacritty-110728.log"
[2020-11-17 09:30:38.847791800] [INFO] Welcome to Alacritty                               search | ST131801 | 09:30, 17/11
[2020-11-17 09:30:38.854792100] [INFO] Configuration loaded from "C:\Users\1352152\AppData\Roaming\alacritty\alacritty.yml
"
[2020-11-17 09:30:38.865791900] [DEBUG] Estimated DPR: 1.5
[2020-11-17 09:30:38.866791900] [DEBUG] Estimated Cell Size: 14 x 32
[2020-11-17 09:30:38.866791900] [DEBUG] Estimated Dimensions: None
[2020-11-17 09:30:39.015859800] [INFO] Device pixel ratio: 1.5
[2020-11-17 09:30:39.064885500] [INFO] Initializing glyph cache...
[2020-11-17 09:30:39.146883400] [INFO] ... finished initializing glyph cache in 0.0812161s
[2020-11-17 09:30:39.147879000] [INFO] Cell Size: 14 x 32
[2020-11-17 09:30:39.147879000] [INFO] Padding: 0 x 0
[2020-11-17 09:30:39.148879300] [INFO] Width: 1024, Height: 768
[2020-11-17 09:30:39.240875100] [INFO] PTY dimensions: Line(24) x Column(73)
[2020-11-17 09:30:39.328881600] [INFO] Using ConPTY backend
[2020-11-17 09:30:39.329881700] [INFO] Initialisation complete
[2020-11-17 09:30:39.331877800] [DEBUG] Term::resize dimensions unchanged
[2020-11-17 09:30:39.332880900] [INFO] Width: 1024, Height: 768
[2020-11-17 09:30:45.991275900] [DEBUG] [unhandled osc_dispatch]: [['1','2',],['7',],] at line 785
```

**Comment by Adriankhl** [comment]
I can confirm that this is not alacritty's problem, I got this too in Windows terminal

**Comment by space-shell** [comment]
I also have this issue in Wez's terminal

![image](https://user-images.githubusercontent.com/45002601/122740197-a66e7800-d27b-11eb-9193-0ccae5cf9838.png)

**Comment by HenryHK** [comment]
I can still reproduce this issue using WSL2 on Windows 10, running neovim nightly 0.6.1_1 and alacritty 0.9.0. Windows terminal can reproduce this issue as well.

As suggested by @space-shell , once I enforced alacritty to use dGPU of my machine it seems the problem has gone. Not sure it's a WSL or neovim thing.

**Comment by domi-eck** [comment]
This problem still exists. I am Using WSL2 on Windows 10 with Nvim 0.9.
