### ISSUE TITLE
Unable to use on Fedora

### ISSUE THREAD

**Issue by cx0der** [jwilm/alacritty#2264]
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | Linux Fedora 29 |
| Rust Version     | stable 1.33.0 |
| Display Server   | Wayland |
| Window Manager   | Gnome |
| Compositor       |  |

# Summary
I tried building from sources as well as running prebuilt binaries from github release page. Whenever I launch alacritty I get this on the console at the bottom of the screen.

```
Created log file at "/tmp/Alacritty-3951.log"
[2019-04-07 11:04] [ERROR] Problem with config: font.offset.x: invalid type: floating point `0`, expected i8 at line 68 column 8; using default value
[2019-04-07 11:04] [ERROR] Problem with config: font.offset.y: invalid type: floating point `0`, expected i8 at line 69 column 8; using default value
[2019-04-07 11:04] [ERROR] Problem with config: font.glyph_offset.x: invalid type: floating point `0`, expected i8 at line 75 column 8; using default value
[2019-04-07 11:04] [ERROR] Problem with config: font.glyph_offset.y: invalid type: floating point `0`, expected i8 at line 76 column 8; using default value
[2019-04-07 11:04] [WARN] Config dimensions is deprecated; please use window.dimensions instead
[2019-04-07 11:04] [WARN] Config padding is deprecated; please use window.padding instead
[2019-04-07 11:04] [WARN] Config custom_cursor_colors is deprecated
[2019-04-07 11:04] [WARN] Config hide_cursor_when_typing is deprecated; please use mouse.hide_when_typing instead
```

# Behavior
I see these errors and warnings on the console as well as at the bottom of alacritty window. If follow the instructions to install and try to launch I see the errors for the first time, and only see a blank screen second launch onwards.

# Expectation
Should work without these issues

# Extra
Screenshot

![image](https://user-images.githubusercontent.com/277487/55679463-ab101580-5929-11e9-8a53-886f2d6fd324.png)

Happy to add more info.

**Comment by chrisduerr** [comment]
Due to differences between the different distributions and dynamic linking, it's not possible for Alacritty to support every platform with a single executable. If you wish for a precompiled binary, native binary, that should probably be addressed with your distribution's package maintainers.

It is planned to potentially support the latest Fedora version (see https://github.com/jwilm/alacritty/issues/2126), however this would only mean support for the latest Fedora version, if you're not using that there's no plan to add explicit support with a precompiled binary from our side.

In the short term your only option is to either rely on installing a non-native version like the snap or to compile Alacritty from source.

**Comment by cx0der** [comment]
My first attempt was to build from source, and I still see the same problem. Consider reopening the issue.

**Comment by chrisduerr** [comment]
Oh sorry, I completely misread your issue.

You should fix the errors in your config and the warnings will disappear. If you haven't changed your config you can also delete it and a new one will be generated automatically.

If that doesn't work, let me know and I'll re-open. Sorry for the miscommunication here.

**Comment by cx0der** [comment]
Yes, that worked, when I deleted the config file from $HOME/.alacritty.yml as well as $HOME/.config/alacritty directory. Thanks for the help and keep up the good work.
