### ISSUE TITLE
Blank lines after each line when pasting from Wayland GTK applications into Vim

### ISSUE THREAD

**Issue by codebam** [jwilm/alacritty#2844]
Which operating system does the issue occur on?

Fedora 30 x86_64

If on linux, are you using X11 or Wayland?

Wayland, using gnome-shell. Also reproducible under sway with wlroots.

**Description:** When pasting from any GTK app running with a Wayland backend (firefox, gedit, gnome-terminal) into Vim inside Alacritty, newlines are added after each line that is pasted.

**How to reproduce:**

1. Open Alacritty inside Sway
1. Start Vim with no configuration (vim defaults) `vim -u NONE`
1. Disable legacy compatibility `:set nocompatible`
1. Paste a block of code from any other GTK Wayland app (firefox, gedit, gnome-terminal) into Vim

**What happens:** There are blank lines after each pasted line in Vim.

**What I expected to happen:** Lines would be pasted as they were copied.

**Comment by zsugabubus** [comment]
I think this one is not related to `alacritty` but `wl-clipboard` (do you use it, right?). Press `i CTRL-R CTRL-O +` and you should see some `^M`s (carriage return).

**Comment by kchibisov** [comment]
We are not using `wl-clipboard` in any way. I've already fixed the bug upstream, so I'm just waiting for a version bump of `smithay-clipboard` to get a fix into `alacritty`.

**Comment by zsugabubus** [comment]
Ah, bracketed paste. Then it's an issue around `vim`. NeoVim used [this patch](https://github.com/neovim/neovim/pull/10877/commits/bf4df9dfa305f0f6c30eab8044145290d69f912b).

**Comment by kchibisov** [comment]
@zsugabubus I don't understand about what are you talking.

The bug was in `GTK` transforming all `\n` and `\r` into `\r\n` on every store for `text/plain;charset=utf-8` mime type and we're loading text to `alacritty` without any normalization (`GTK` normalizes every `\r\n` and `\r` on every load to `\n` for this mime type). So we need to perform `LF` normalization on every load as well as `GTK` does, since they're doing it for more then a decade. It just happened, that on Wayland we should handle such things ourselves.

>Then it's an issue around Vim.

This is not a bug in vim/neovim, etc app. On unix the line terminator is `LF` not `CRLF`, so vim/neovim are doing fine here.

And as I said before, no more information is being required for this bug to be fixed, it's just a matter of time when `smithay-clipboard`(our Wayland clipboard provider) gets a version bump, since the patch is already upstream. In case we're eager to get this bug fixed, I could vendor `smithay-clipboard` myself and use my own fork in `alacritty`.

**Comment by zsugabubus** [comment]
I just wanted to give a one-line explanation what are those blank lines, nothing fancy.

> On unix the line terminator is LF not CRLF, so vim/neovim are doing fine here.

As I linked above, NeoVim fixed the behavior, so I'm not sure they did absolutely fine before. *vim can be prepared for `\r\n` line-endings on all platforms, I don't think it's such a big deal.

> for more information Smithay/smithay-clipboard#9

I saw it thanks, but the issue will still persist with Vim if somebody use the clipboard (`"+p`...). (Personally, I never used bracketed paste with Vim, that's why I first thought that it's Vim's clipboard functionality that we are talking about and said that it's probably an issue with `wl-clipboard`.)

**Comment by kchibisov** [comment]
Those blank lines a from `GTK` apps no more no less.

FYI the problem is not only with vim, it's with **every** app (fish, zsh, bash, neomutt, etc). If you use `vim`'s clipboard option and it inserts new lines then it's a vim problem, not ours. This issue is about our `Ctrl+Shift+V`/`middle mouse button` paste problem, which inserts new lines, when you're pasting text from GTK apps on Wayland (e.g. Firefox).

For our paste we're just writing clipboard content to pty, depending on the current terminal mode (BRACKETED_PASTE or not)
https://github.com/jwilm/alacritty/blob/679e67d045f60d528c695a1ee8a6c0f3d6feeda1/alacritty/src/input.rs#L217
content
>I saw it thanks, but the issue will still persist with Vim if somebody use the clipboard ("+p...). (Personally, I never used bracketed paste with Vim, that's why I first thought that it's Vim's clipboard functionality that we are talking about and said that it's probably an issue with wl-clipboard.)

You're misunderstanding the issue. This is a vim problem, not ours. The fix I've send resolves our problem with GTK apps. Vim is just an example here.

>Then it's an issue around Vim. NeoVim used this patch.

This patch is for neovim's clipboard and has nothing to do with this issue.

**Comment by zsugabubus** [comment]
> the problem is not only with vim, it's with every app

> This patch is for neovim's clipboard and has nothing to do with this issue.

I understand it correctly. I'm not against fixing it _also_ in `smithay-clipboard` or anything else if you thought so.

I approached the issue from the consumer side and just showed how they defended against `\r\n` ourselves (so they don't depend on that _all_ terminals convert `\r\n` -> `\n`). I think it can expected that a text editor or anything else that expects lines can handle `\r\n` correctly.

**Comment by chrisduerr** [comment]
> I'm just waiting for a version bump of smithay-clipboard to get a fix into alacritty.

@kchibisov Have you suggested releasing a new version upstream?

**Comment by kchibisov** [comment]
@chrisduerr I don't, but it's already in a state when every commit is a version bump, so probably it was decided to wait for more patches. I'm not comfortable with asking folks to release a new version after each patch I'm sending to them, since it's just rude imho. I think, if you want to obtain latest changes, then vendor things yourself and don't bother someone to increase a version number of a package just for you, unless bumping will make sense, like security issue or general bug fix (my patch is non of them). However we could just use a git master with a specific commit instead of creating our own fork.

**Comment by chrisduerr** [comment]
> I don't, but it's already in a state when every commit is a version bump, so probably it was decided to wait for more patches.

That's for a very good reason though, because there's not much activity on the repository. You don't want to have fixes just sitting around forever on a repository with low activity.

> like security issue or general bug fix (my patch is none of them)

How is your patch not a bug fix?

> I'm not comfortable with asking folks to release a new version after each patch I'm sending to them, since it's just rude imho.

Sure, asking for new releases when there has been a conscious decision not to make one is annoying and doesn't help anyone, but I don't think that's the case here. I doubt there will be any other commits within the next month at least, so waiting for multiple commits to bulk them together doesn't make a lot of sense.

The smithay-clipoard library has been generously written by trimental for use in Alacritty and afaik we are the only consumer. Trimental and vberger are also always very cooperative and I'm sure they'd be willing to talk about it. So while in general you're probably right, but things are a little bit different here.

@kchibisov Are there any other contributions we'd want to make in the near future? Otherwise there likely won't be any update to the library anytime soon and I'll head over on IRC myself and talk to levanx if he's around.

**Comment by kchibisov** [comment]
>How is your patch not a bug fix?

It's a bug fix, but not that important as gtk primary selection one. That's why I've added a "general", since without gtk protocol clipboard was limited in its use under some compositors.

>Otherwise there likely won't be any update to the library anytime soon and I'll head over on IRC myself and talk to levanx if he's around.

I don't think so, since it's need a massive rework and with pending??? changes to SCTK I'd like to avoid doing it now, so go ahead and ask them.

**Comment by chrisduerr** [comment]
> I don't think so, since it's need a massive rework and with pending??? changes to SCTK I'd like to avoid doing it now, so go ahead and ask them.

Ah, I wasn't aware of it. Though I'm not sure if that's a 'we need to rework it now', or 'we want to rework it eventually'. But I'll ask about that on IRC, that will likely be easier.

**Comment by alxckn** [comment]
I am still experiencing this issue on Fedora 32 (wayland) with gnome (3.36) and alacritty 0.6.0.

If I copy/paste from sublime text or gedit, I have new lines inserted in between each line.
![image](https://user-images.githubusercontent.com/11556013/102468779-41c72c00-4052-11eb-9ece-01b040b68ef5.png)
becomes
![image](https://user-images.githubusercontent.com/11556013/102468838-53a8cf00-4052-11eb-9d6d-41ae0918e4b4.png)

Is there a configuration option I am missing or is it something that could be fixed by building from the sources?
Thanks for your help
