### ISSUE TITLE
Cannot switch languages with keyboard shortcut

### ISSUE THREAD

**Issue by trimailov** [jwilm/alacritty#948]
OS: macOS 10.12.6

As the title says. If I focus `Alacritty.app` and it has wrong input source language, I cannot change it with keyboard shortcut.

Related: https://github.com/jwilm/alacritty/pull/945 , https://github.com/jwilm/alacritty/issues/909

Created this as a new issue, to not bloat up #909 and this issue may not be only related to macOS.

**Comment by chrisduerr** [comment]
As far as I know this problem is only related to MacOS. At least I haven't been able to reproduce anything similar to this on linux.

Is this actually fixed with #945?

**Comment by trimailov** [comment]
The language input memorisation works with #945, though keyboard shortcut to change the language does not work. 

In my case its `alt + cmd + space` and what happens is that space is entered in the input. No language change.

**Comment by chrisduerr** [comment]
I'm sure you could set that up as a command in alacritty, right?

**Comment by zindel** [comment]
@trimailov what macOS version are you at? Works for me on Sierra 10.12 just fine (with the Cmd+Space switch shortcut)

**Comment by trimailov** [comment]
@zindel 

> OS: macOS 10.12.6

I've changed my input source shortcut to `cmd+space` and I still can't change language when alacritty is in focus.

Can't see any keybinding in `~/.config/alacritty/alacritty.yml` for `cmd+space` either. 

Interestingly enough I have `cmd+space` bind to show spotlight search and this shortcut works as expected when alacritty is in focus.

**Comment by melonmanchan** [comment]
I think this is also the same issue as is apparent in #935

**Comment by trimailov** [comment]
@melonmanchan thanks, have not stumbled upon that issue during the search (should've used `OSX` and not `macOS` for searching :) ).

I am closing this issue then.
