### ISSUE TITLE
LC_CTYPE set to some strange (invalid?) value in alacritty

### ISSUE THREAD

**Issue by giorgiga** [jwilm/alacritty#993]
(macOS, current master branch)

My `.bashrc` sets `LANG=en_GB.UTF-8` and `LC_COLLATE=C`; in `terminal.app` I get:

<img width="458" alt="t" src="https://user-images.githubusercontent.com/471835/34543150-c40853d0-f0df-11e7-947e-b23ae50ae1d3.png">

In `alacritty` `LC_CTYPE` is set to `en_GB@currency=EUR.UTF-8`:

<img width="386" alt="a" src="https://user-images.githubusercontent.com/471835/34543167-dd072b18-f0df-11e7-90a8-059def995195.png">

I guess the value of `LC_CTYPE` somehow comes from my macOS setting (where I have overridden £ with €), but it doesn't seem valid (at least, it causes `nano` to not correctly display unicode files) and I do not expect my locale settings to be impacted by launching a terminal.

Also, in `alacritty` I get a `__CF_USER_TEXT_ENCODING=0x1F5:0:0`, which is absent in `terminal.app`.

**Comment by jwilm** [comment]
We're using [`localeIdentifier`](https://developer.apple.com/documentation/foundation/nslocale/1416263-localeidentifier?language=objc) to get the locale. Perhaps we should specifically request `countryCode` and `languageCode`, join them, and use that to avoid getting the additional locale data.

**Comment by giorgiga** [comment]
Oh, `LANG` and `LC_TYPE` are set in `locale.rs`: didn't see that.

Then I guess the issue is, that appending ".UTF-8" to `localeIdentifier` is not general enough for people with weird settings like me. 😄 

I don't know very much about desktop programming (I do web mostly), but... why setting locale variables at all?
To me that doesn't *feel* like something a terminal should do.

**Comment by jwilm** [comment]
> To me that doesn't feel like something a terminal should do.

It's a macOS thing 😐

**Comment by giorgiga** [comment]
> It's a macOS thing 😐

Indeed iterm does set `LANG` and `LC_CTYPE`, too (see below for details) - do you remember why that is needed in macOS?

### Iterm

Iterm sets `LANG` to `en_GB` by concatenating (`"{}_{}"`) the two

    NSString* languageCode = [[NSLocale currentLocale] objectForKey:NSLocaleLanguageCode];
    NSString* countryCode = [[NSLocale currentLocale] objectForKey:NSLocaleCountryCode];

If that fails (either is null) it uses `localeIdentifier` (which I assume would yield to `LANG="en_GB@currency=EUR.UTF-8"` in my case).

Iterm also sets `LC_CTYPE`, however it seems to set it to the encoding only and only if it is valid (ie: accepted by `setlocale`).

the setting of both variables can be disabled via settings.

### Terminal.app
Terminal.app does *not* set `LC_CTYPE`, but It does set `LANG` (to `en_GB.UTF-8`).

That is, with the preferences:
<img width="667" alt="terminal" src="https://user-images.githubusercontent.com/471835/34570573-75ad0220-f16c-11e7-90a4-7f165409586b.png">

**Comment by jwilm** [comment]
> do you remember why that is needed in macOS?

Without setting them, macOS doesn't seem to source the bash_profile or per user shell configuration. The terminal would start at the root directory `/` and generally feel really broken. On Linux, these environment variables are already present from the parent process.

Nice research on this! I think I would lean towards continuing to set `LC_CTYPE` simply because iTerm does so by default. It can always be overridden from a .bashrc or something.

I think the fix here is to generate `"{languageCode}_{countryCode}.UTF8` and use it for both `LC_CTYPE` and `LANG`.

**Comment by giorgiga** [comment]
Agreed: that would work flawlessly even with my weird config!

To me it would make sense to not touch `LANG` and `LC_CTYPE` if they are already defined in the environment (for  `LC_CTYPE` "when `locale LC_CTYPE` prints anything" would make even more sense).
Not sure if there is an actual use case though.

As pure speculation, I think setting `LC_CTYPE` to  just `UTF-8` would actually do the same thing as setting it to `<locale>.UTF-8`, as

> The LC_CTYPE category shall define character classification, case conversion, and other character attributes [[source](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap07.html#tag_07_03_01)]

and Unicode defines all those things in a language-agnostic way.

**Comment by meck** [comment]
Alacritty right now sets `LANG` and `LC_CTYPE` to `en_SE.UTF-8` according to the Mac settings for me and that is fine for `LANG`. But dosen't work for setlocale it seems, just `UTF-8` works fine and that is what both iterm and terminal.app sets it to.
So I would agree about that being a better option...

**Comment by giorgiga** [comment]
Apparently setting `LC_CTYPE` to `UTF-8` only (ie: no *language* part) can cause issues on Linux.

I changed my dotfiles after my last comment and, while `LC_CTYPE=UTF-8` works fine on macOS, on Void Linux `bash` complains with `-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory`.

**Comment by meck** [comment]
I Looked at some other terminals, it seems iterm, terminal and kitty dosen't set `LC_CTYPE` as a environment variable at all on my system at least , although it is inferred by setlocale.

```
$ echo $LC_CTYPE

$ echo $LANG
sv_SE.UTF-8
$ locale
LANG="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_CTYPE="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_ALL=
```

**Comment by sodiumjoe** [comment]
So I tried to take a stab at this: https://github.com/sodiumjoe/alacritty/commit/ed61fa43581a60c3f42c816ea4010736705ee469

Doing what @jwilm suggested above in https://github.com/jwilm/alacritty/issues/993#issuecomment-355357010

But I'm getting really weird results:

```~ ➤ locale
LANG="en_US@currency=USD.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
~ ➤ echo $LANG
en_US@currency=USD.UTF-8
~ ➤ echo $LC_CTYPE
en_US@currency=USD.UTF-8
~ ➤
```

adding a `println` right before the two `env::set_var` calls shows the correct value (for me `en_US.UTF-8`).

So yeah, I'm pretty confused.

**Comment by sodiumjoe** [comment]
it looks to me like [iterm only sets `LANG`](https://github.com/gnachman/iTerm2/blob/79aff4d59fd591e7628649bcabe5f27541740bf6/sources/PTYSession.m#L1703), so I tried that, too, with the exact same results.

**Comment by giorgiga** [comment]
...and I don't seem to be able to reproduce the issue anymore? - either in master or in @sodiumjoe branch.

Quite puzzling. 

Am I doing something wrong or was it some weirdness that they fixed in a recent macOS update?

@sodiumjoe:

What macOS version are you on?
Mine is 10.13.3 (17D47)

How do you reproduce, @sodiumjoe?

I add:

```
echo =====
echo "LANG: $LANG"
echo "LC_CTYPE: $LC_CTYPE"
echo "locale"
locale
echo =====
```

to the head of my `.bashrc` (ie: before I set `LANG` myself), unset all locale-relate variables and launch alacritty.

I get this output - no @currency weirdness anymore:

````
=====
LANG: en_GB.UTF-8
LC_CTYPE: 
locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
=====
````

PS: @sodiumjoe it seems very strange looking at your code that `println` is correct but then $LANG is not - can you double check that you are testing on a clean build?

**Comment by sodiumjoe** [comment]
I think I figured it out. I had alacritty starting directly into `tmux` with:

```
shell:
  program: /usr/local/bin/tmux
  args:
    - attach
```

in my `alacritty.yml`. Apparently that does weird stuff with the locale. When I change it to `zsh --login` it works fine. So I guess I'll have to figure out some other way to start directly in tmux. I'll make a PR with the branch I have.

**Comment by sodiumjoe** [comment]
after a bit more experimentation, it looks like tmux keeps the value for the duration of a tmux server. `tmux kill-server` between trying different builds confirms that my PR fixes this issue.

**Comment by chrisduerr** [comment]
Can anyone reproduce this after `tmux kill-server` or even better a complete restart? Otherwise I'd close this issue.

**Comment by sodiumjoe** [comment]
Sorry, to be clear, I can still reproduce the issue after a `tmux kill-server`. The issue is fixed with [this pr](https://github.com/jwilm/alacritty/pull/1087).

tmux is orthogonal to the issue, it was just interfering with my repro. When I take tmux out of the equation completely, but setting alacritty to start with `zsh --login`, I can reliably reproduce the issue, and it's reliably fixed in my PR.

**Comment by chrisduerr** [comment]
But then it should be fine once that's merged. :)

**Comment by doy-stripe** [comment]
not sure if this is related (it seems slightly different than the other issues here), but currently for me, alacritty is setting `LANG` and `LC_CTYPE` to `en-US.UTF-8` instead of `en_US.UTF-8`, which causes applications to not be able to understand it.

**Comment by sodiumjoe** [comment]
Yeah that looks wrong. Can you try #1087 and see if that fixes it?

**Comment by doy-stripe** [comment]
yup, #1087 looks like it works for me

**Comment by ktk** [comment]
Not sure what I'm doing wrong but I'm on `alacritty 0.2.7` and I seem to have the issue still on MacOS:

                                                                                        1 ↵
```
> locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

From what I understand this should be set correctly now by alacritty itself, correct?

**Comment by ktk** [comment]
Nevermind, I did not had LANG set in my zshrc, works now
